#!/usr/bin/expect -f

trap {
  set rows [stty rows]
  set cols [stty columns]
  stty rows $rows columns $cols < $spawn_out(slave,name)
} WINCH

set keyf [lindex $argv 0]
set user [lindex $argv 1]
set host [lindex $argv 2]
set args [lrange $argv 3 $argc]
set timeout -1

log_user 0
spawn scripts/gd $keyf
expect -re "(.*)\r"
set pass $expect_out(1,string)

log_user 1
spawn ssh $user@$host $args
match_max 100000
expect "*?assword:*"
send -- "$pass\r"
interact
